const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

/**
 * Git Handler for managing git operations and repository setup
 */
class GitHandler {
  constructor(reporter) {
    this.reporter = reporter;
  }

  /**
   * Check if git is available
   */
  isGitAvailable() {
    try {
      execSync('git --version', { stdio: 'ignore' });
      return true;
    } catch (error) {
      return false;
    }
  }

  /**
   * Check if directory is already a git repository
   */
  isGitRepository(projectPath) {
    return fs.existsSync(path.join(projectPath, '.git'));
  }

  /**
   * Initialize a new git repository
   */
  async initRepository(projectPath, options = {}) {
    const { force = false, initialBranch = 'main' } = options;

    if (!this.isGitAvailable()) {
      this.reporter.warn('Git is not available. Skipping repository initialization.');
      return { success: false, reason: 'git_not_available' };
    }

    if (this.isGitRepository(projectPath) && !force) {
      this.reporter.info('Git repository already exists');
      return { success: true, existing: true };
    }

    const spinner = this.reporter.startSpinner('Initializing git repository...');

    try {
      // Initialize repository
      execSync(`git init -b ${initialBranch}`, {
        cwd: projectPath,
        stdio: 'pipe'
      });

      // Configure git settings (basic)
      this.setupGitConfig(projectPath);

      // Create initial commit
      this.createInitialCommit(projectPath);

      spinner.succeed('Git repository initialized');
      
      return {
        success: true,
        branch: initialBranch,
        commits: 1
      };

    } catch (error) {
      spinner.fail('Failed to initialize git repository');
      throw new Error(`Git initialization failed: ${error.message}`);
    }
  }

  /**
   * Setup basic git configuration
   */
  setupGitConfig(projectPath) {
    try {
      // Check if global git config exists
      try {
        execSync('git config --global user.name', { stdio: 'pipe' });
      } catch (error) {
        // No global config, set a default
        this.reporter.warn('No global git user configured. Please set up your git identity:');
        this.reporter.info('  git config --global user.name "Your Name"');
        this.reporter.info('  git config --global user.email "your.email@example.com"');
      }

      // Set local git attributes for the project
      const gitAttributes = `# Auto detect text files and perform LF normalization
* text=auto

# Binary files
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.ico binary
*.pdf binary
*.zip binary
*.tar.gz binary

# Font files
*.woff binary
*.woff2 binary
*.ttf binary
*.eot binary

# Video files
*.mp4 binary
*.avi binary
*.mov binary
*.wmv binary

# Lock files should always use LF
package-lock.json text eol=lf
yarn.lock text eol=lf
pnpm-lock.yaml text eol=lf
`;

      fs.writeFileSync(path.join(projectPath, '.gitattributes'), gitAttributes);

    } catch (error) {
      this.reporter.warn(`Failed to setup git config: ${error.message}`);
    }
  }

  /**
   * Create initial commit
   */
  createInitialCommit(projectPath) {
    try {
      // Add all files
      execSync('git add .', {
        cwd: projectPath,
        stdio: 'pipe'
      });

      // Create initial commit
      execSync('git commit -m "🎉 Initial commit - Generated by MERN AI CLI"', {
        cwd: projectPath,
        stdio: 'pipe'
      });

    } catch (error) {
      this.reporter.warn(`Failed to create initial commit: ${error.message}`);
    }
  }

  /**
   * Create comprehensive .gitignore file
   */
  createGitignore(projectPath, config) {
    const gitignoreContent = this.generateGitignoreContent(config);
    
    fs.writeFileSync(path.join(projectPath, '.gitignore'), gitignoreContent);
    
    this.reporter.success('.gitignore file created');
    
    return gitignoreContent;
  }

  /**
   * Generate .gitignore content based on project configuration
   */
  generateGitignoreContent(config) {
    const sections = [];

    // Dependencies
    sections.push('# Dependencies');
    sections.push('node_modules/');
    sections.push('npm-debug.log*');
    sections.push('yarn-debug.log*');
    sections.push('yarn-error.log*');
    sections.push('pnpm-debug.log*');
    sections.push('lerna-debug.log*');
    sections.push('');

    // Runtime and build outputs
    sections.push('# Runtime and build outputs');
    sections.push('dist/');
    sections.push('build/');
    sections.push('.next/');
    sections.push('out/');
    sections.push('.vite/');
    sections.push('.nuxt/');
    sections.push('.cache/');
    sections.push('.parcel-cache/');
    sections.push('');

    // Environment and configuration
    sections.push('# Environment and configuration');
    sections.push('.env');
    sections.push('.env.local');
    sections.push('.env.development.local');
    sections.push('.env.test.local');
    sections.push('.env.production.local');
    sections.push('');

    // Logs
    sections.push('# Logs');
    sections.push('logs/');
    sections.push('*.log');
    sections.push('');

    // Database
    if (config.database?.type === 'sqlite') {
      sections.push('# Database');
      sections.push('*.sqlite');
      sections.push('*.sqlite3');
      sections.push('*.db');
      sections.push('');
    }

    // File uploads and temporary files
    sections.push('# File uploads and temporary files');
    sections.push('uploads/');
    sections.push('temp/');
    sections.push('tmp/');
    sections.push('*.tmp');
    sections.push('');

    // IDE and editor files
    sections.push('# IDE and editor files');
    sections.push('.vscode/');
    sections.push('.idea/');
    sections.push('*.swp');
    sections.push('*.swo');
    sections.push('*~');
    sections.push('');

    // OS generated files
    sections.push('# OS generated files');
    sections.push('.DS_Store');
    sections.push('.DS_Store?');
    sections.push('._*');
    sections.push('.Spotlight-V100');
    sections.push('.Trashes');
    sections.push('ehthumbs.db');
    sections.push('Thumbs.db');
    sections.push('');

    // Testing
    sections.push('# Testing');
    sections.push('coverage/');
    sections.push('.nyc_output/');
    sections.push('');

    // Package manager lock files (keep only one)
    sections.push('# Package manager lock files (uncomment the ones you want to ignore)');
    sections.push('# package-lock.json');
    sections.push('# yarn.lock');
    sections.push('# pnpm-lock.yaml');
    sections.push('# bun.lockb');
    sections.push('');

    // Docker
    if (config.deployment?.docker) {
      sections.push('# Docker');
      sections.push('.dockerignore');
      sections.push('');
    }

    // Cloud deployment
    if (config.deployment?.platform) {
      sections.push('# Deployment');
      sections.push('.vercel');
      sections.push('.netlify');
      sections.push('');
    }

    return sections.join('\n');
  }

  /**
   * Setup git hooks
   */
  async setupGitHooks(projectPath, config) {
    const hooksDir = path.join(projectPath, '.git', 'hooks');
    
    if (!fs.existsSync(hooksDir)) {
      return { success: false, reason: 'not_git_repo' };
    }

    const hooks = [];

    // Pre-commit hook for linting
    if (config.features?.includes('linting')) {
      const preCommitHook = this.generatePreCommitHook(config);
      const preCommitPath = path.join(hooksDir, 'pre-commit');
      
      fs.writeFileSync(preCommitPath, preCommitHook, { mode: 0o755 });
      hooks.push('pre-commit');
    }

    // Commit message hook
    const commitMsgHook = this.generateCommitMsgHook();
    const commitMsgPath = path.join(hooksDir, 'commit-msg');
    
    fs.writeFileSync(commitMsgPath, commitMsgHook, { mode: 0o755 });
    hooks.push('commit-msg');

    this.reporter.success(`Git hooks setup: ${hooks.join(', ')}`);
    
    return {
      success: true,
      hooks
    };
  }

  /**
   * Generate pre-commit hook
   */
  generatePreCommitHook(config) {
    return `#!/bin/sh
# Pre-commit hook generated by MERN AI CLI

echo "Running pre-commit checks..."

# Check if we're in a git repository
if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
    echo "Not in a git repository"
    exit 1
fi

# Run linting if available
if [ -f "package.json" ]; then
    if npm run lint:check >/dev/null 2>&1; then
        echo "Running linter..."
        npm run lint:check || {
            echo "Linting failed. Please fix the issues and try again."
            exit 1
        }
    fi
    
    # Run tests if available
    if npm run test:unit >/dev/null 2>&1; then
        echo "Running unit tests..."
        npm run test:unit || {
            echo "Tests failed. Please fix the issues and try again."
            exit 1
        }
    fi
fi

echo "Pre-commit checks passed!"
exit 0
`;
  }

  /**
   * Generate commit message hook
   */
  generateCommitMsgHook() {
    return `#!/bin/sh
# Commit message hook generated by MERN AI CLI

commit_regex='^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\\(.+\\))?: .{1,50}'

if ! grep -qE "$commit_regex" "$1"; then
    echo "Invalid commit message format!"
    echo "Please use the conventional commit format:"
    echo "  type(scope): description"
    echo ""
    echo "Types: feat, fix, docs, style, refactor, test, chore, perf, ci, build, revert"
    echo "Example: feat(auth): add user registration"
    exit 1
fi
`;
  }

  /**
   * Get repository status
   */
  getRepositoryStatus(projectPath) {
    if (!this.isGitRepository(projectPath)) {
      return { isRepo: false };
    }

    try {
      const status = execSync('git status --porcelain', {
        cwd: projectPath,
        encoding: 'utf8'
      });

      const branch = execSync('git rev-parse --abbrev-ref HEAD', {
        cwd: projectPath,
        encoding: 'utf8'
      }).trim();

      const commitCount = execSync('git rev-list --count HEAD', {
        cwd: projectPath,
        encoding: 'utf8'
      }).trim();

      return {
        isRepo: true,
        branch,
        commitCount: parseInt(commitCount),
        hasChanges: status.length > 0,
        changes: status.split('\n').filter(line => line.trim())
      };

    } catch (error) {
      return {
        isRepo: true,
        error: error.message
      };
    }
  }

  /**
   * Add remote origin
   */
  addRemote(projectPath, remoteUrl, remoteName = 'origin') {
    try {
      execSync(`git remote add ${remoteName} ${remoteUrl}`, {
        cwd: projectPath,
        stdio: 'pipe'
      });

      this.reporter.success(`Remote '${remoteName}' added: ${remoteUrl}`);
      
      return { success: true, remote: remoteName, url: remoteUrl };

    } catch (error) {
      throw new Error(`Failed to add remote: ${error.message}`);
    }
  }
}

module.exports = GitHandler;
