const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

/**
 * Security Handler for managing project security configurations
 * Handles environment variables, API keys, and security best practices
 */
class SecurityHandler {
  constructor(reporter) {
    this.reporter = reporter;
  }

  /**
   * Generate secure environment variables
   */
  generateSecureEnvVars(config) {
    const envVars = {};

    // Generate JWT secrets
    envVars.JWT_SECRET = this.generateSecureSecret(64);
    envVars.JWT_REFRESH_SECRET = this.generateSecureSecret(64);

    // Generate session secrets
    envVars.SESSION_SECRET = this.generateSecureSecret(32);

    // Generate encryption keys
    envVars.ENCRYPTION_KEY = this.generateSecureSecret(32);

    // Database configuration
    if (config.database?.type === 'mongodb') {
      envVars.MONGODB_URI = config.database.connectionString || 'mongodb://localhost:27017/your-app-name';
    } else if (config.database?.type === 'postgresql') {
      envVars.DATABASE_URL = config.database.connectionString || 'postgresql://username:password@localhost:5432/your-app-name';
    }

    // Redis configuration (if caching is enabled)
    if (config.features?.includes('caching') || config.features?.includes('sessions')) {
      envVars.REDIS_URL = 'redis://localhost:6379';
    }

    // Email configuration (if email features are enabled)
    if (config.features?.includes('email')) {
      envVars.SMTP_HOST = 'your-smtp-host';
      envVars.SMTP_PORT = '587';
      envVars.SMTP_USER = 'your-email@example.com';
      envVars.SMTP_PASS = 'your-email-password';
    }

    // Cloud storage (if file upload is enabled)
    if (config.features?.includes('fileUpload')) {
      envVars.CLOUDINARY_CLOUD_NAME = 'your-cloudinary-cloud-name';
      envVars.CLOUDINARY_API_KEY = 'your-cloudinary-api-key';
      envVars.CLOUDINARY_API_SECRET = 'your-cloudinary-api-secret';
    }

    // Payment gateway (if payments are enabled)
    if (config.features?.includes('payments')) {
      envVars.STRIPE_SECRET_KEY = 'sk_test_your-stripe-secret-key';
      envVars.STRIPE_PUBLISHABLE_KEY = 'pk_test_your-stripe-publishable-key';
      envVars.STRIPE_WEBHOOK_SECRET = 'whsec_your-webhook-secret';
    }

    // OAuth providers
    if (config.auth?.providers?.includes('google')) {
      envVars.GOOGLE_CLIENT_ID = 'your-google-client-id';
      envVars.GOOGLE_CLIENT_SECRET = 'your-google-client-secret';
    }

    if (config.auth?.providers?.includes('github')) {
      envVars.GITHUB_CLIENT_ID = 'your-github-client-id';
      envVars.GITHUB_CLIENT_SECRET = 'your-github-client-secret';
    }

    // API configuration
    envVars.API_BASE_URL = config.deployment?.environment === 'production' 
      ? 'https://your-domain.com/api'
      : 'http://localhost:5000/api';

    envVars.CLIENT_URL = config.deployment?.environment === 'production'
      ? 'https://your-domain.com'
      : 'http://localhost:3000';

    // Security headers
    envVars.CORS_ORIGIN = envVars.CLIENT_URL;
    envVars.RATE_LIMIT_MAX = '100';
    envVars.RATE_LIMIT_WINDOW = '900000'; // 15 minutes

    return envVars;
  }

  /**
   * Generate a cryptographically secure secret
   */
  generateSecureSecret(length = 32) {
    return crypto.randomBytes(length).toString('hex');
  }

  /**
   * Create environment files
   */
  async createEnvironmentFiles(projectPath, config) {
    const envVars = this.generateSecureEnvVars(config);
    
    // Create .env file
    const envContent = this.generateEnvFileContent(envVars, 'development');
    await this.writeEnvFile(path.join(projectPath, '.env'), envContent);

    // Create .env.example file (with placeholder values)
    const exampleEnvVars = this.createExampleEnvVars(envVars);
    const exampleContent = this.generateEnvFileContent(exampleEnvVars, 'development');
    await this.writeEnvFile(path.join(projectPath, '.env.example'), exampleContent);

    // Create .env.production.example
    const prodEnvVars = { ...exampleEnvVars };
    prodEnvVars.NODE_ENV = 'production';
    prodEnvVars.API_BASE_URL = 'https://your-production-domain.com/api';
    prodEnvVars.CLIENT_URL = 'https://your-production-domain.com';
    
    const prodContent = this.generateEnvFileContent(prodEnvVars, 'production');
    await this.writeEnvFile(path.join(projectPath, '.env.production.example'), prodContent);

    this.reporter.success('Environment files created');
    
    return {
      envVars,
      files: ['.env', '.env.example', '.env.production.example']
    };
  }

  /**
   * Generate environment file content
   */
  generateEnvFileContent(envVars, environment) {
    const lines = [];
    
    lines.push(`# Environment: ${environment}`);
    lines.push(`# Generated by MERN AI CLI on ${new Date().toISOString()}`);
    lines.push('');
    
    lines.push('# Application Configuration');
    lines.push(`NODE_ENV=${environment}`);
    lines.push(`PORT=${environment === 'production' ? 5000 : 5000}`);
    lines.push('');

    // Group related variables
    const groups = {
      'Security': ['JWT_SECRET', 'JWT_REFRESH_SECRET', 'SESSION_SECRET', 'ENCRYPTION_KEY'],
      'Database': ['MONGODB_URI', 'DATABASE_URL'],
      'Cache & Sessions': ['REDIS_URL'],
      'Email Configuration': ['SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASS'],
      'File Storage': ['CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET'],
      'Payment Gateway': ['STRIPE_SECRET_KEY', 'STRIPE_PUBLISHABLE_KEY', 'STRIPE_WEBHOOK_SECRET'],
      'OAuth Providers': ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GITHUB_CLIENT_ID', 'GITHUB_CLIENT_SECRET'],
      'API Configuration': ['API_BASE_URL', 'CLIENT_URL', 'CORS_ORIGIN'],
      'Rate Limiting': ['RATE_LIMIT_MAX', 'RATE_LIMIT_WINDOW']
    };

    for (const [groupName, groupVars] of Object.entries(groups)) {
      const groupValues = groupVars.filter(key => envVars[key]);
      
      if (groupValues.length > 0) {
        lines.push(`# ${groupName}`);
        groupValues.forEach(key => {
          lines.push(`${key}=${envVars[key]}`);
        });
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /**
   * Create example environment variables (with placeholder values)
   */
  createExampleEnvVars(envVars) {
    const example = {};
    
    for (const [key, value] of Object.entries(envVars)) {
      if (key.includes('SECRET') || key.includes('KEY')) {
        example[key] = 'your-secure-secret-here';
      } else if (key.includes('URI') || key.includes('URL')) {
        example[key] = value.includes('localhost') ? value : 'your-service-url-here';
      } else if (key.includes('CLIENT_ID')) {
        example[key] = 'your-oauth-client-id';
      } else if (key.includes('USER') || key.includes('PASS')) {
        example[key] = 'your-credentials-here';
      } else {
        example[key] = value;
      }
    }
    
    return example;
  }

  /**
   * Write environment file with proper permissions
   */
  async writeEnvFile(filePath, content) {
    fs.writeFileSync(filePath, content, { mode: 0o600 });
  }

  /**
   * Setup security configurations
   */
  async setupSecurityConfig(projectPath, config) {
    const results = [];

    // Create environment files
    const envResult = await this.createEnvironmentFiles(projectPath, config);
    results.push(envResult);

    // Create security configuration file
    const securityConfig = this.generateSecurityConfig(config);
    const securityConfigPath = path.join(projectPath, 'server', 'config', 'security.js');
    
    // Ensure config directory exists
    fs.mkdirSync(path.dirname(securityConfigPath), { recursive: true });
    fs.writeFileSync(securityConfigPath, securityConfig);
    
    results.push({
      type: 'security-config',
      file: 'server/config/security.js'
    });

    this.reporter.success('Security configuration completed');
    
    return results;
  }

  /**
   * Generate security configuration file
   */
  generateSecurityConfig(config) {
    return `const rateLimit = require('express-rate-limit');
const helmet = require('helmet');
const cors = require('cors');

// Security configuration
const securityConfig = {
  // Rate limiting
  rateLimit: rateLimit({
    windowMs: parseInt(process.env.RATE_LIMIT_WINDOW) || 15 * 60 * 1000, // 15 minutes
    max: parseInt(process.env.RATE_LIMIT_MAX) || 100, // limit each IP to 100 requests per windowMs
    message: 'Too many requests from this IP, please try again later.',
    standardHeaders: true,
    legacyHeaders: false,
  }),

  // CORS configuration
  cors: cors({
    origin: process.env.CORS_ORIGIN?.split(',') || ['http://localhost:3000'],
    credentials: true,
    optionsSuccessStatus: 200
  }),

  // Helmet security headers
  helmet: helmet({
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
        fontSrc: ["'self'", "https://fonts.gstatic.com"],
        imgSrc: ["'self'", "data:", "https:"],
        scriptSrc: ["'self'"],
        connectSrc: ["'self'", "https://api.stripe.com"]
      }
    },
    crossOriginEmbedderPolicy: false
  }),

  // JWT configuration
  jwt: {
    secret: process.env.JWT_SECRET,
    refreshSecret: process.env.JWT_REFRESH_SECRET,
    expiresIn: '15m',
    refreshExpiresIn: '7d'
  },

  // Session configuration
  session: {
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: false,
    cookie: {
      secure: process.env.NODE_ENV === 'production',
      httpOnly: true,
      maxAge: 24 * 60 * 60 * 1000 // 24 hours
    }
  }
};

module.exports = securityConfig;
`;
  }

  /**
   * Validate security setup
   */
  validateSecuritySetup(projectPath) {
    const requiredFiles = ['.env', '.env.example'];
    const missingFiles = [];

    for (const file of requiredFiles) {
      if (!fs.existsSync(path.join(projectPath, file))) {
        missingFiles.push(file);
      }
    }

    if (missingFiles.length > 0) {
      throw new Error(`Missing security files: ${missingFiles.join(', ')}`);
    }

    this.reporter.success('Security setup validation passed');
    return true;
  }
}

module.exports = SecurityHandler;
